base_url = "https://tommyrharper.github.io/"
title = "Tom Harper"
description = "Tom Harper's Personal Website"
default_language = "en"
theme = "serene"
output_dir = "public"
compile_sass = true
minify_html = false # Keep this false, as it may cause issues with some styles
build_search_index = false # Keep this false, search is temporarily unsupported
generate_feeds = false # Whether to generate a feed file in root, read docs for more info about rss feed
feed_filenames = ["feed.xml"] # "feed.xml" | "atom.xml" | "rss.xml", read docs for more info
taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]
render_emoji = false
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false
github_alerts = true

[markdown.highlighting]
style = "class"
light_theme = "github-light"
dark_theme = "github-dark"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

#=========================================================================================

[extra]

nav = [
  { name = "about", path = "/about" },
  { name = "posts", path = "/posts" },
#  { name = "tags", path = "/tags" },
#  { name = "github", path = "https://github.com/tommyrharper" }, 
]

# Your info on the home page, if you don't want to display handle/bio/avatar, simply comment out that line
name = "Tom Harper"
handle = "tommyrharper"
# bio = "Student"
# avatar = "img/avatar.webp"
links = [
  { name = "GitHub", icon = "github", url = "https://github.com/tommyrharper" },
  { name = "LinkedIn", icon = "linkedin", url = "https://www.linkedin.com/in/thomas-robert-harper" },
#   { name = "Email", icon = "email", url = "mailto:<your-email-address>" },
#  { name = "Twitter", icon = "twitter", url = "https://twitter.com/<your-username>" },
#  { name = "Mastodon", icon = "mastodon", url = "https://mastodon.social/<your-username>", rel_me = true },
]
blog_section_path = "/posts" # Path of the main blog section, used by home page's recent posts and tags pages

back_link_text = "Back" # Text of the back button
color_scheme = "auto" # "auto" | "light" | "dark"

# og_image = "img/og.png" # The default image for social media sharing (Open Graph), a path in static folder or a full URL

footer_copyright = "© 2025 Thomas Harper"
footer_credits = true # Whether to show "Built with zola and serene" in footer

not_found_error_text = "404 Not Found"
not_found_recover_text = "« back to home »"

# Site-wide default values of display options, can be overridden in a section's `_index.md`, and again in a post's front-matter
date_format = "%b %-d, %Y"
toc = true # show table-of-contents
code_copy = true # show copy button in code block
comment = false # enable comment
math = true # enable formula rendering with KaTeX
mermaid = false # enable chart rendering with Mermaid
outdated_alert = false # show outdate alert after certain days
outdated_alert_days = 120
outdated_alert_text_before = "This article was last updated "
outdated_alert_text_after = " days ago and may be out of date."

reaction = false # Whether to enable anonymous emoji reactions (Note: You need to set up a working api endpoint to enable this feature)
reaction_align = "right" # "left" | "center" | "right"
reaction_endpoint = "https://example.com/api/reaction"
